### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [yuhonas/zsh-ansimotd#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by yuhonas** [comment]
Done! see https://github.com/yuhonas/zsh-ansimotd/commit/9a64d398fd5cffad3a7ca7529232b1190158901f
