### ISSUE TITLE
Suggestion: A command to delete the last motd that was loaded

### ISSUE THREAD

**Issue by mainsm** [yuhonas/zsh-ansimotd#11]
A lot of the ANSI art is great, but some of it is garbage.  It would be nice if there were a command that could delete the last loaded MOTD so it won't show up anymore.  Or maybe just export the selected MOTD to an environment variable so that people can choose what to do with it themselves like edit it or whatever.

**Comment by yuhonas** [comment]
Yeah there's a definitely a pretty wide mix among some art packs, the full path to the ANSI shown for the session is available in the ENV variable `ANSI_MOTD_FILENAME` see also the section in the [README.md](https://github.com/yuhonas/zsh-ansimotd#damn-that-piece-of-ansi-art-that-just-got-shown-was-awesome-which-one-was-it) so something obviously like this should do it :-
```
rm "$ANSI_MOTD_FILENAME" 
```
I need to add it to the README (as I only just discovered it) but this is a great spot for ANSI art https://16colo.rs/ and provides rsync/ftp support for bulk ANSI art downloading through rsync/ftp eg. `rsync rsync://16colo.rs/pack/1994/acdu0194/raw/`

**Comment by yuhonas** [comment]
Closing this one out, feel free to reopen if you have further questions
