### ISSUE TITLE
Typo in ansi_art_download function

### ISSUE THREAD

**Issue by marfit** [yuhonas/zsh-ansimotd#2]
There is a typo at:

https://github.com/yuhonas/zsh-ansimotd/blob/273c250b8473cac00e000af35bed477fe7337454/zsh-ansimotd.plugin.zsh#L17

Between `level=` and `1`  shouldn't be a blank character or the wget command doesn't work.

Otherwise, great stuff!

**Comment by yuhonas** [comment]
Cheers, nice catch!
