### ISSUE TITLE
ANSI art is garbled because of wordwrap.

### ISSUE THREAD

**Issue by mainsm** [yuhonas/zsh-ansimotd#5]
Wordwrap can cause the ansi art to be badly distorted.  This is especially the case in small terminals like Termux.

On reddit, a user named romkatv came up with a solution.  https://www.reddit.com/r/zsh/comments/12ueb6b/comment/jhmlgez/?utm_source=share&utm_medium=web2x&context=3

Disable wordwrap before printing the art and then reenable it after.

print -n '\e[?7l'  # turn off automatic margins (a.k.a. line wrapping) 
iconv -f 437 < $ansi_filename
print -n '\e[?7h'  # restore automatic margins

I'd have submitted this as a PR, but I didn't write the original code.

**Comment by yuhonas** [comment]
Thanks for posting this! i've put up a fix here https://github.com/yuhonas/zsh-ansimotd/pull/6 with an option to opt out of line wrapping disabling if for some reason you need to, it _sounds_ like a sensible default though just erring on the side of other use cases I may not be aware of

**Comment by yuhonas** [comment]
This is now the exception you need to _opt in_ for, I feel small fixed screen sizes are the exception, i've also updated the README accordingly - https://github.com/yuhonas/zsh-ansimotd/commit/405c4c0b537e17ad8c8d8e9c0df68af5e5c921cb
